### ISSUE TITLE
Doesn't install with cordova-android 9.0.0

### ISSUE THREAD

**Issue by rcpinheiro** [ahmedwahba/cordova-plugin-drawoverapps#13]
Hi!
The plugin seems to require a very old cordova-android version, is it possible to update,please? Thanks!

> Installing "cordova-plugin-drawoverapps" for android
Installing "cordova-plugin-compat" for android
Plugin doesn't support this project's cordova-android version. cordova-android: 9.0.0, failed version requirement:
      <6.3.0
Skipping 'cordova-plugin-compat' for android
Subproject Path: CordovaLib
Subproject Path: app
Failed to install 'cordova-plugin-drawoverapps': TypeError: Cannot read property 'PACKAGE_NAME'...

**Comment by ahmedwahba** [comment]
try again with last update 1.1.0

**Comment by DigitalDevelooper** [comment]
Hi, can you maybe help me with this error? I am using Cordova-android 9.0.0 and already installed Cordova-plugin-device the log looks like this:


`BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed in version 5.0 of the Android Gradle plugin.
For more information, see http://d.android.com/r/tools/update-dependency-configurations.html.

> Task :app:compileDebugJavaWithJavac FAILED
C:\#Develooper\cordova app\dt\platforms\android\app\src\main\java\org\apache\cordova\overApps\Services\OverAppsService.java:81: error: cannot find symbol
         overAppsHead = inflater.inflate(R.layout.service_over_apps_head, null, false);
                                          ^
  symbol:   variable layout
  location: class R
C:\#Develooper\cordova app\dt\platforms\android\app\src\main\java\org\apache\cordova\overApps\Services\OverAppsService.java:82: error: cannot find symbol
         overAppsView = inflater.inflate(R.layout.service_over_apps_view, null, false);
                                          ^
  symbol:   variable layout
  location: class R
C:\#Develooper\cordova app\dt\platforms\android\app\src\main\java\org\apache\cordova\overApps\Services\OverAppsService.java:83: error: cannot find symbol
         webView = (WebView) overAppsView.findViewById(R.id.webView);
                                                           ^
  symbol:   variable webView
  location: class id
C:\#Develooper\cordova app\dt\platforms\android\app\src\main\java\org\apache\cordova\overApps\Services\OverAppsService.java:84: error: cannot find symbol
         imageHead = (ImageView) overAppsHead.findViewById(R.id.imageHead);
                                                               ^
  symbol:   variable imageHead
  location: class id
C:\#Develooper\cordova app\dt\platforms\android\app\src\main\java\org\apache\cordova\overApps\Services\OverAppsService.java:85: error: cannot find symbol
         imgClose = (ImageView) overAppsView.findViewById(R.id.imgClose);
                                                              ^
  symbol:   variable imgClose
  location: class id
C:\#Develooper\cordova app\dt\platforms\android\app\src\main\java\org\apache\cordova\overApps\Services\OverAppsService.java:219: error: cannot find symbol
             keyDispatureView = inflater.inflate(R.layout.key_dispature, null, false);
                                                  ^
  symbol:   variable layout
  location: class R
C:\#Develooper\cordova app\dt\platforms\android\app\src\main\java\org\apache\cordova\overApps\Services\OverAppsService.java:221: error: cannot find symbol
         rlKeyDispature = (KeyDispatchLayout) keyDispatureView.findViewById(R.id.tab_left);
                                                                                ^
  symbol:   variable tab_left
  location: class id
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
7 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
22 actionable tasks: 22 executed
Command failed with exit code 1: C:\#Develooper\cordova app\dt\platforms\android\gradlew cdvBuildDebug -b C:\#Develooper\cordova app\dt\platforms\android\build.gradle
PS C:\#Develooper\cordova app\dt>`

**Comment by ahmedwahba** [comment]
#4
