### ISSUE TITLE
Error: Cannot read property 'PACKAGE_NAME' of undefined

### ISSUE THREAD

**Issue by akshgods** [ahmedwahba/cordova-plugin-drawoverapps#2]
cordova versions: 6.0.0
and 7.0.1 latest both are tested

when installing its giving an error
Error: Cannot read property 'PACKAGE_NAME' of undefined

**Comment by ahmedwahba** [comment]
is **cordova-plugin-device** installed in your project ?

**Comment by akshgods** [comment]
ok thanks, after device plugin this error has gone  . but not understand how its works, can you please provide demo app for this.

**Comment by ahmedwahba** [comment]
this is just a quick example in ionic 1 
https://github.com/ahmedwahba/overApp-example
