### ISSUE TITLE
deviceready has not fired after 5 seconds.

### ISSUE THREAD

**Issue by minchemo** [ahmedwahba/cordova-plugin-drawoverapps#6]
I am running on Cordova@7.1.0 and android@6.3.0 , the widget can be opened but I cant call any function on the new html page even a alert .
(OverApps.closeWebView(); This is work.)

I have checked the inspect on chrome dev tools , it shows 

> deviceready has not fired after 5 seconds.

This is my html . I think this plugin is work but the deviceready can be only fired once , anyone can help ?

```
<!DOCTYPE html>
<html>
    <head>
		<link rel="manifest" href="manifest.json">
        <title></title>
    </head>	
  <body>
		<button onclick="closeOverApp()">here</button>
		<button onclick="ss()">heresss</button>
                <script type="text/javascript" src="js/index.js"></script>
		<script type="text/javascript" src="js/script.js"></script>
		<script type="text/javascript" src="cordova.js"></script>
  </body>
</html>
```

**Comment by ATMEGA17** [comment]
Hey any chance that you solved this problem ?

**Comment by ahmedwahba** [comment]
if you need to add any JS function to work attach it to window object or you need to call it from native android part as **closeWebView()** works

**Comment by ATMEGA17** [comment]
Thank you for your respond the problem is that i cannot acces to cordova plugins it said undefined each time i call a plugin for example
window.plugin......

is there a way to acces cordova plugins from the webview ??

**Comment by ATMEGA17** [comment]
and for the closeWebView() it works  because  you attached it at a javascript interface inside the webview  is there a way to acces all cordova plugins ?

**Comment by ahmedwahba** [comment]
webview acts as standalone dependent service so it can't access plugins , i am searching if their a way to do so

**Comment by besmartness** [comment]
> and for the closeWebView() it works because you attached it at a javascript interface inside the webview is there a way to acces all cordova plugins ?

Did you solve this issue ? I'm facing such issue now.

**Comment by besmartness** [comment]
> webview acts as standalone dependent service so it can't access plugins , i am searching if their a way to do so

Have you find solution for this issue ??

**Comment by ahmedwahba** [comment]
Why do you stick to over app service to do your staff,It's just a feature inside your app. 
You also know services always has limitations from OS so as fast solution, you can relaunch your app itself (even with deep linking ) then use needed plugins

**Comment by besmartness** [comment]
> Why do you stick to over app service to do your staff,It's just a feature inside your app.
> You also know services always has limitations from OS so as fast solution, you can relaunch your app itself (even with deep linking ) then use needed plugins

Thanks for your quick reply!

is it possible to relaunch app inside draw.html ???

**Comment by besmartness** [comment]
Long stroy short, I'm making an app which detects incoming call and at this moment draw.html should appears. inside of draw.html there are several inputs like first_name and surname...etc when click the "save" button informations should be saved to app's storage.

In my case All the functionalities are working fine and draw.html appears while incoming call, but I cannot save the informations to the storage...

**Comment by ahmedwahba** [comment]
Deep linking should be useful in your case if you add all call info to a link that opens on your app [read more here for deep linking ](https://ionicframework.com/docs/native/deeplinks) then inside your app control storing everything
